In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt
from imutils import paths

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [2]:
dataset =r'C:\Users\Dostam\FaceMask Detection\Dataset'
imagePaths=list(paths.list_images(dataset))

In [3]:
imagePaths

['C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000000.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000001.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000002.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000003.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000004.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000005.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000006.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000007.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000008.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000009.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\00000_Mask.jpg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000010.jpeg',
 'C:\\Users\\Dostam\\FaceMask Detection\\Dataset\\Face_Mask\\000011.jpeg',
 'C:\\Users\\Dostam\\F

In [4]:
data = []
labels = []

for i in imagePaths:
    label = i.split(os.path.sep)[-2]
    labels.append(label)
    image = load_img(i,target_size=(224,224))
    image = img_to_array(image)
    image = preprocess_input(image)
    data.append(image)

In [5]:
data

[array([[[-0.78039217, -0.56078434, -0.372549  ],
         [-0.78039217, -0.60784316, -0.42745095],
         [-0.78039217, -0.6156863 , -0.46666664],
         ...,
         [ 0.12941182,  0.45098042,  0.7019608 ],
         [ 0.20000005,  0.48235297,  0.7490196 ],
         [ 0.22352946,  0.5058824 ,  0.77254903]],
 
        [[-0.78039217, -0.56078434, -0.372549  ],
         [-0.78039217, -0.60784316, -0.44313723],
         [-0.78039217, -0.6156863 , -0.46666664],
         ...,
         [ 0.12156868,  0.4431373 ,  0.69411767],
         [ 0.17647064,  0.48235297,  0.7411765 ],
         [ 0.20000005,  0.5058824 ,  0.7647059 ]],
 
        [[-0.78039217, -0.56078434, -0.38823527],
         [-0.79607844, -0.6156863 , -0.47450978],
         [-0.7882353 , -0.62352943, -0.49019605],
         ...,
         [ 0.09803927,  0.41960788,  0.67058825],
         [ 0.16078436,  0.48235297,  0.73333335],
         [ 0.19215691,  0.5137255 ,  0.7647059 ]],
 
        ...,
 
        [[ 0.3411765 ,  0.4666667 

In [6]:
labels

['Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face_Mask',
 'Face

In [7]:
data = np.array(data,dtype='float32')
labels = np.array(labels)

In [8]:
data.shape

(1916, 224, 224, 3)

In [9]:
lb=LabelBinarizer()
labels = lb.fit_transform(labels)
labels = to_categorical(labels)

In [10]:
labels

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [11]:
train_X,test_X,train_Y,test_Y = train_test_split(data,labels,test_size=0.20,random_state=10,stratify=labels)

In [12]:
train_X

array([[[[-0.94509804, -0.92156863, -0.64705884],
         [-0.9764706 , -0.8509804 , -0.654902  ],
         [-0.8901961 , -0.7411765 , -0.40392154],
         ...,
         [-0.94509804, -0.96862745, -0.88235295],
         [-0.9529412 , -0.96862745, -0.88235295],
         [-0.9607843 , -0.96862745, -0.90588236]],

        [[-0.8666667 , -0.88235295, -0.5921569 ],
         [-0.92156863, -0.8039216 , -0.62352943],
         [-0.827451  , -0.6784314 , -0.42745095],
         ...,
         [-0.94509804, -0.96862745, -0.88235295],
         [-0.9529412 , -0.9764706 , -0.8901961 ],
         [-0.9607843 , -0.96862745, -0.90588236]],

        [[-0.79607844, -0.8666667 , -0.7176471 ],
         [-0.90588236, -0.88235295, -0.62352943],
         [-0.6862745 , -0.62352943, -0.3333333 ],
         ...,
         [-0.9529412 , -0.9764706 , -0.8901961 ],
         [-0.94509804, -0.9607843 , -0.8745098 ],
         [-0.96862745, -0.9764706 , -0.9137255 ]],

        ...,

        [[-0.77254903, -0.88235295, -0

In [13]:
train_Y

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [14]:
train_X.shape

(1532, 224, 224, 3)

In [15]:
train_Y.shape

(1532, 2)

In [16]:
test_X.shape

(384, 224, 224, 3)

In [17]:
test_Y.shape

(384, 2)

In [18]:
aug = ImageDataGenerator(rotation_range=20, zoom_range=0.15, width_shift_range=0.2, height_shift_range=0.2, shear_range=0.15, horizontal_flip=True, vertical_flip=True, fill_mode='nearest')

In [19]:
aug

In [20]:
baseModel = MobileNetV2(weights='imagenet',include_top=False, input_tensor=Input(shape=(224,224,3)))

In [21]:
baseModel.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
__________________________________________________________________________________________________
Conv1_relu (ReLU)               (None, 112, 112, 32) 0           bn_Conv1[0][0]                   
_______________________________________________________________________________

In [22]:
headModel = baseModel.output
headModel = AveragePooling2D(pool_size=(7,7))(headModel)
headModel = Flatten(name="Flatten")(headModel)
headModel = Dense(128, activation='relu')(headModel)
headModel = Dropout(0.5)(headModel)
headModel = Dense(2,activation='softmax')(headModel)

model = Model(inputs=baseModel.input, outputs=headModel)

In [23]:
for layer in baseModel.layers:
    layer.trainable = False

In [24]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
__________________________________________________________________________________________________
Conv1_relu (ReLU)               (None, 112, 112, 32) 0           bn_Conv1[0][0]                   
______________________________________________________________________________________________

In [25]:
learning_rate = 0.0001
Epochs = 10 
BS = 12

opt = Adam(lr=learning_rate, decay= learning_rate/Epochs)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

H = model.fit(
    aug.flow(train_X,train_Y,batch_size=BS),
    steps_per_epoch = len(train_X)//BS,
    validation_data=(test_X,test_Y),
    validation_steps=len(test_X)//BS,
    epochs = Epochs
)

model.save(r'C:\Users\Dostam\FaceMask Detection\mobilenet_v2.model')

Epoch 1/10
127/127 [==============================] - 105s 705ms/step - loss: 0.6906 - accuracy: 0.6267 - val_loss: 0.4248 - val_accuracy: 0.8568
Epoch 2/10
127/127 [==============================] - 104s 817ms/step - loss: 0.4735 - accuracy: 0.8127 - val_loss: 0.3341 - val_accuracy: 0.8802
Epoch 3/10
127/127 [==============================] - 92s 725ms/step - loss: 0.4121 - accuracy: 0.8513 - val_loss: 0.2871 - val_accuracy: 0.8906
Epoch 4/10
127/127 [==============================] - 89s 698ms/step - loss: 0.3686 - accuracy: 0.8513 - val_loss: 0.2608 - val_accuracy: 0.9036
Epoch 5/10
127/127 [==============================] - 92s 721ms/step - loss: 0.3621 - accuracy: 0.8430 - val_loss: 0.2478 - val_accuracy: 0.9115
Epoch 6/10
127/127 [==============================] - 84s 659ms/step - loss: 0.3141 - accuracy: 0.8982 - val_loss: 0.2326 - val_accuracy: 0.9089
Epoch 7/10
127/127 [==============================] - 83s 651ms/step - loss: 0.2895 - accuracy: 0.8952 - val_loss: 0.2153 - val_

In [26]:
predict = model.predict(test_X,batch_size=BS)
predict = np.argmax(predict, axis=1)
print(classification_report(test_Y.argmax(axis=1),predict,target_names=lb.classes_))

              precision    recall  f1-score   support

   Face_Mask       0.92      0.92      0.92       195
 Face_NoMask       0.92      0.92      0.92       189

    accuracy                           0.92       384
   macro avg       0.92      0.92      0.92       384
weighted avg       0.92      0.92      0.92       384

